language: android
android:
  components:
  - tools
  - platform-tools
  - android-25
  - build-tools-25.0.0
  - extra-android-m2repository
  - extra-android-support

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

env:
  - ANDROID_NDK_HOME="$ANDROID_HOME/ndk-bundle"

before_install:
  - mkdir $ANDROID_HOME/licenses
  - echo -ne "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
  - $ANDROID_HOME/tools/bin/sdkmanager "ndk-bundle"
  - $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.6.4111459"
