language: android
android:
  components:
  - tools
  - platform-tools
  - android-25
  - build-tools-25.0.0
  - extra-android-m2repository
  - extra-android-support

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

env:
  - ANDROID_NDK_HOME="$ANDROID_HOME/ndk-bundle"

before_install:
  - mkdir $ANDROID_HOME/licenses
  - echo -ne "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee" >> $ANDROID_HOME/licenses/android-sdk-license
  - echo -ne "\n79120722343a6f314e0719f863036c702b0e6b2a\n84831b9409646a918e30573bab4c9c91346d8abd" >> $ANDROID_HOME/licenses/android-sdk-preview-license
  - $ANDROID_HOME/tools/bin/sdkmanager "ndk-bundle"
  - $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.6.4111459"
  - $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-28"
